apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: services # specific namespace where services are deployed
subjects:
- kind: User
  name: dev 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole 
  name: dev-user-role 
  apiGroup: rbac.authorization.k8s.io 